"""initial

Revision ID: 24b01de10aa6
Revises: 
Create Date: 2025-10-01 01:58:42.254607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b01de10aa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('orchestra', 'quartet', 'quintet', name='ensembletype').create(op.get_bind())
    sa.Enum('performer', 'composer', 'conductor', 'director', name='musiciantype').create(op.get_bind())
    op.create_table('compositions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compositions'))
    )
    op.create_table('ensembles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.Column('ensemble_type', postgresql.ENUM('orchestra', 'quartet', 'quintet', name='ensembletype', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ensembles'))
    )
    op.create_table('musicians',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.Column('musician_type', postgresql.ENUM('performer', 'composer', 'conductor', 'director', name='musiciantype', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_musicians'))
    )
    op.create_table('records',
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('wholesale_company_address', sa.String(length=100), nullable=False),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('current_year_sold', sa.Integer(), nullable=False),
    sa.Column('last_year_sold', sa.Integer(), nullable=False),
    sa.Column('remaining_stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_table('musician_ensemble',
    sa.Column('musician_id', sa.Integer(), nullable=True),
    sa.Column('ensemble_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensemble_id'], ['ensembles.id'], name=op.f('fk_musician_ensemble_ensemble_id_ensembles')),
    sa.ForeignKeyConstraint(['musician_id'], ['musicians.id'], name=op.f('fk_musician_ensemble_musician_id_musicians'))
    )
    op.create_table('performances',
    sa.Column('performance_date', sa.Date(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], name=op.f('fk_performances_composition_id_compositions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performances'))
    )
    op.create_table('performance_record',
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name=op.f('fk_performance_record_performance_id_performances')),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_performance_record_record_id_records'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_record')
    op.drop_table('performances')
    op.drop_table('musician_ensemble')
    op.drop_table('records')
    op.drop_table('musicians')
    op.drop_table('ensembles')
    op.drop_table('compositions')
    sa.Enum('performer', 'composer', 'conductor', 'director', name='musiciantype').drop(op.get_bind())
    sa.Enum('orchestra', 'quartet', 'quintet', name='ensembletype').drop(op.get_bind())
    # ### end Alembic commands ###
