"""ondelete cascade

Revision ID: 4809958bc24f
Revises: 5a41fdb62b9e
Create Date: 2025-10-01 21:03:34.543356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4809958bc24f'
down_revision: Union[str, Sequence[str], None] = '5a41fdb62b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_musician_ensemble_ensemble_id_ensembles'), 'musician_ensemble', type_='foreignkey')
    op.drop_constraint(op.f('fk_musician_ensemble_musician_id_musicians'), 'musician_ensemble', type_='foreignkey')
    op.create_foreign_key(op.f('fk_musician_ensemble_ensemble_id_ensembles'), 'musician_ensemble', 'ensembles', ['ensemble_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk_musician_ensemble_musician_id_musicians'), 'musician_ensemble', 'musicians', ['musician_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('fk_performance_record_performance_id_performances'), 'performance_record', type_='foreignkey')
    op.drop_constraint(op.f('fk_performance_record_record_id_records'), 'performance_record', type_='foreignkey')
    op.create_foreign_key(op.f('fk_performance_record_record_id_records'), 'performance_record', 'records', ['record_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk_performance_record_performance_id_performances'), 'performance_record', 'performances', ['performance_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('fk_performances_ensemble_id_ensembles'), 'performances', type_='foreignkey')
    op.drop_constraint(op.f('fk_performances_composition_id_compositions'), 'performances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_performances_composition_id_compositions'), 'performances', 'compositions', ['composition_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk_performances_ensemble_id_ensembles'), 'performances', 'ensembles', ['ensemble_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_performances_ensemble_id_ensembles'), 'performances', type_='foreignkey')
    op.drop_constraint(op.f('fk_performances_composition_id_compositions'), 'performances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_performances_composition_id_compositions'), 'performances', 'compositions', ['composition_id'], ['id'])
    op.create_foreign_key(op.f('fk_performances_ensemble_id_ensembles'), 'performances', 'ensembles', ['ensemble_id'], ['id'])
    op.drop_constraint(op.f('fk_performance_record_performance_id_performances'), 'performance_record', type_='foreignkey')
    op.drop_constraint(op.f('fk_performance_record_record_id_records'), 'performance_record', type_='foreignkey')
    op.create_foreign_key(op.f('fk_performance_record_record_id_records'), 'performance_record', 'records', ['record_id'], ['id'])
    op.create_foreign_key(op.f('fk_performance_record_performance_id_performances'), 'performance_record', 'performances', ['performance_id'], ['id'])
    op.drop_constraint(op.f('fk_musician_ensemble_musician_id_musicians'), 'musician_ensemble', type_='foreignkey')
    op.drop_constraint(op.f('fk_musician_ensemble_ensemble_id_ensembles'), 'musician_ensemble', type_='foreignkey')
    op.create_foreign_key(op.f('fk_musician_ensemble_musician_id_musicians'), 'musician_ensemble', 'musicians', ['musician_id'], ['id'])
    op.create_foreign_key(op.f('fk_musician_ensemble_ensemble_id_ensembles'), 'musician_ensemble', 'ensembles', ['ensemble_id'], ['id'])
    # ### end Alembic commands ###
